name: Continuous Integration - Reusable
on: [workflow_call]
jobs:
  CI_Steps:
    runs-on: [self-hosted]
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - run: echo OK
        name: Code Lints
#      - run: echo OK
#        name: Code Build
      - run: npm install
        name: Install NodeJs modules
      - run: echo npm run test:unit
        name: Code Unit Tests
      - run: echo npm run test:integration
        name: Code Integration Tests
      - run: echo OK
        name: Code Review
      - run: echo OK
        name: Release Software